- README.md
Thanks for the previous merge!  I realized that there was a missing line from the README, so here's the fix.  Sorry for not catching it sooner.
> Fixing README syntax error

- lib/logstash-logger/device/redis.rb
- spec/device/redis_spec.rb
The URI parser puts a path param into the options hash, this is not handled correctly by the redis client.
This is a fix for issue #41
> Add handling of path option in redis client

- lib/logstash-logger/device.rb
- spec/device_spec.rb
previously any non uri options passed to a device would be stripped out. This makes the behavior consistent with how the Rails configuration works.
> fix to allow configuration of other values via uri

- lib/logstash-logger/cee_formatter.rb
This creates a CEE style formatter which can be used with syslog-ng, and other devices that take logs in CEE format.
I'm using it in conjunction with a service from here:  https://apps.sematext.com
With this configuration:  
```
LogStashLogger.configure do | logconfig| 
logconfig.customize_event do | event|
event["logsene-app-token"]= ENV['logsene_app_token']
end
end
config.logger = LogStashLogger.new(type: :tcp, host: 'logsene-receiver-syslog.sematext.com', port: 514)
config.logger.formatter = LogStashLogger::CeeFormatter.new 
```
It works great.
> Added cee formatter.

- README.md
- lib/logstash-logger/device.rb
- lib/logstash-logger/device/balancer.rb
- lib/logstash-logger/device/multi_delegator.rb
- lib/logstash-logger/formatter.rb
- lib/logstash-logger/logger.rb
- lib/logstash-logger/multi_logger.rb
- logstash-logger.gemspec
- spec/device/balancer_spec.rb
- spec/device/file_spec.rb
- spec/device/io_spec.rb
- spec/device/multi_delegator_spec.rb
- spec/device/socket_spec.rb
- spec/device/unix_spec.rb
- spec/device_spec.rb
- spec/formatter_spec.rb
- spec/multi_logger_spec.rb
- spec/rails_spec.rb
- spec/spec_helper.rb
The new `:multi_logger` type writes log messages to multiple loggers. Each logger can have its own formatter.
Fixes #52
> Support for multiple loggers

- README.md
- lib/logstash-logger/logger.rb
- logstash-logger.gemspec
- samples/syslog.conf
- spec/syslog_spec.rb
This uses `Syslog::Logger`, which is built into the Ruby 2+ standard library, and available as a separate gem in Ruby 1.9. Note that this is a separate logger rather than a device.
Fixes #50
> Support for logging to syslog

- README.md
- lib/logstash-logger/device/connectable.rb
- lib/logstash-logger/device/kafka.rb
- lib/logstash-logger/device/redis.rb
- lib/logstash-logger/device/tcp.rb
- spec/device/unix_spec.rb
- spec/spec_helper.rb
This throws connectable log devices (such as TCP, UDP, and Redis) behind `Stud::Buffer` in an attempt to improve reliability. In my testing, I have verified that log messages do get buffered, and will retry if an exception is thrown.
However, I have found that sockets don't always raise an exception right away when the server side of the socket is closed. See http://stackoverflow.com/questions/2530652/ruby-tcpsocket-doesnt-notice-it-when-server-is-killed and https://www.ruby-forum.com/topic/148532. This means that some messages will inevitably get lost. Logstash does not return any sort of reply to acknowledge that it received the message, so it's impossible to tell if the message was sent successfully if no exception is raised.
Log messages are written out one at a time. This way, if an …
> Buffer connectable log devices

- lib/logstash-logger/multi_logger.rb
- spec/multi_logger_spec.rb
> Prevent formatter of each logger in MultiLogger from being overridden with the default

- lib/logstash-logger/logger.rb
- spec/syslog_spec.rb
Syslog is unavailable on Windows. Autoloading Syslog is therefore a bad idea, since this results in a LoadError if the Syslog constant is ever referenced on a Windows machine.
Fixes #64
> Fix configuration on Windows

- lib/logstash-logger/configuration.rb
- lib/logstash-logger/formatter/base.rb
This mitigates the issue with UDP packet size limits. (https://github.com/dwbutler/logstash-logger/issues/78)
> Provide `max_message_size` option

- lib/logstash-logger/device/connectable.rb
- lib/logstash-logger/device/kafka.rb
- lib/logstash-logger/device/redis.rb
LogStashLogger currently uses `Stud::Buffer` to implement buffering for connectable devices (such as TCP, Redis, etc.) When the remote service goes down, an exception is raised when a buffer flush is attempted. By default `Stud::Buffer` will retry sending the messages forever. Since a flush is triggered when a message is received, or on a regular timer, this will cause logging calls to block. See https://github.com/jordansissel/ruby-stud/issues/28
`Stud::Buffer` allows callbacks to be fired when it encounters a flush error. This ties into that mechanism to abort the flush and re-enqueue the failed messages. This behavior is now enabled by default. To instead drop messages when there is a flush error, pass the new `drop_messages_on_flush_error` option to the logger.
Most applications will …
> Allow log messages to be dropped

- lib/logstash-logger/configuration.rb
- lib/logstash-logger/device/base.rb
- lib/logstash-logger/device/connectable.rb
- lib/logstash-logger/device/kafka.rb
- lib/logstash-logger/device/redis.rb
Internal refactoring to make all error logging go through an error logger. The default error logger logs to STDERR, but a custom error logger can be provided by passing a new `error_logger` option or by changing `LogStashLogger.configuration.default_error_logger`.
> Unify error logging

- lib/logstash-logger/device/balancer.rb
- lib/logstash-logger/device/base.rb
- lib/logstash-logger/device/connectable.rb
- lib/logstash-logger/device/kafka.rb
- lib/logstash-logger/device/multi_delegator.rb
- lib/logstash-logger/device/redis.rb
- lib/logstash-logger/device/stderr.rb
- lib/logstash-logger/device/stdout.rb
When a reconnecting a connectable device, the connection should first be (safely) closed. This is accomplished by making two changes. First, all devices now have two methods: `close!` (unsafe close without error handling) and `close` (close with error handling). Second, connectable devices can take a new option, `flush: false` to close the connection without flushing messages. Together, this makes it safe to close the connection when reconnecting without losing any messages in case closing fails due to a connection issue.
Fixes https://github.com/dwbutler/logstash-logger/pull/66
> Safely close connection when reconnecting

- README.md
- lib/logstash-logger/logger.rb
- lib/logstash-logger/multi_logger.rb
- lib/logstash-logger/silenced_logging.rb
- spec/multi_logger_spec.rb
- spec/silenced_logging_spec.rb
Adds support for the same `Logger#silence` interface provided by Rails. This was extracted from Rails, but has no dependencies. So the functionality can be used without Rails. The interface is the same as the one provided by Rails.
In the process, I fixed support for tagged logging in `MultiLogger`.
Fixes https://github.com/dwbutler/logstash-logger/issues/86
> Support for logger silencing

- lib/logstash-logger/buffer.rb
- lib/logstash-logger/device/connectable.rb
- logstash-logger.gemspec
Fork and vendor in `Stud::Buffer` in order to customize its behavior better. This eliminates some of the issues with how `Stud::Buffer` was being (ab)used before, namely unpredictable exceptions causing mutex issues, and non-used threads causing the process to crash.
As a side-effect, the new `autoflush` setting, which defaults to false, allows for log messages to truly be buffered and flushed in the background. By default, there should no longer be any blocking behavior or exceptions bubbling up to the process.
This should fix https://github.com/dwbutler/logstash-logger/issues/88
> Custom buffer implementation

- lib/logstash-logger.rb
- When using ActiveSupport inflector by itself (without the rest
of Rails), the Rails module is defined, but Rails::Railtie is not.
This causes an error during bundler bootstrapping
> Only require logstash-logger/railtie if Rails::Railtie is defined

- README.md
- lib/logstash-logger/buffer.rb
- lib/logstash-logger/device/connectable.rb
The current implementation of message buffering puts messages into a queue, and flushes them every five seconds. If the program exits, any messages in the buffer will be lost.
This fixes the issue by automatically flushing the buffer when the program exits. This is done by registering an `at_exit` block which does a final flush, which will wait for all messages to be flushed. If an exception occurs, it will be logged and ignored.
This option is configurable with the new option `buffer_flush_at_exit`, which now defaults to `true`.
Fixes #91
> Flush log messages when exiting

- lib/logstash-logger/logger.rb
- lib/logstash-logger/silenced_logging.rb
LogStashLogger's implementation of `Logger#silence` is derived from `ActiveRecord::SessionStore::Extension::LoggerSilencer`. If `ActiveRecord::SessionStore` is in use, this module gets included into `Logger`. This causes `LogStashLogger::SilencedLogging`'s monkey patching to interfere with the same monkey patching done by `ActiveRecord::SessionStore`.
The solution is to change the names of the monkey patched methods so they don't interfere with the ones defined in `ActiveRecord::SessionStore`.
Fixes #94
> Fix Logger#silence monkey patching

- lib/logstash-logger/buffer.rb
When the buffer state is reset after dropping messages, the mutexes are also reinitialized with new instances. This causes an issue with `buffer_flush` when it tries to unlock the new mutex that it never locked, raising `Attempt to unlock a mutex which is not locked (ThreadError)`.
This fixes the issue by memoizing the buffer mutexes and reusing them even when the buffer state is reset.
Fixes https://github.com/dwbutler/logstash-logger/issues/97
> Memoize buffer mutexes

- lib/logstash-logger/buffer.rb
- lib/logstash-logger/device/connectable.rb
The buffer implementation vendored from `Stud:Buffer` has an internal logger. However, it's called with non-standard arguments not supported by Ruby's standard Logger class. This fixes the issue by logging in the standard way. A new `buffer_logger` configuration variable is also exposed to allow the buffer logger to be set.
Fixes https://github.com/dwbutler/logstash-logger/issues/101
> Fix internal buffer logger

- lib/logstash-logger/device.rb
Without this line, I am not able to add URI specific links.
```
require 'logstash-logger'
logger = LogStashLogger.new(uri: "tcp://example.com:5001")
```
Fails with
```
/Users/bis/.gem/ruby/2.3.3/gems/logstash-logger-0.20.0/lib/logstash-logger/device.rb:40:in `parse_uri_config': uninitialized constant URI (NameError)
from /Users/bis/.gem/ruby/2.3.3/gems/logstash-logger-0.20.0/lib/logstash-logger/device.rb:28:in `build_device'
from /Users/bis/.gem/ruby/2.3.3/gems/logstash-logger-0.20.0/lib/logstash-logger/device.rb:24:in `new'
from /Users/bis/.gem/ruby/2.3.3/gems/logstash-logger-0.20.0/lib/logstash-logger/logger.rb:67:in `build_default_logger'
from /Users/bis/.gem/ruby/2.3.3/gems/logstash-logger-0.20.0/lib/logstash-logger/logger.rb:57:in `build_logger'
from …
```
> Add missing require for URI

- lib/logstash-logger/device/multi_delegator.rb
- lib/logstash-logger/logger.rb
- spec/constructor_spec.rb
- spec/device/multi_delegator_spec.rb
When constructing a `MultiLogger` or `MultiDelegator`, configuration options at the top level are ignored. This behavior is a bit surprising and unexpected. This fixes the issue by merging output configurations into the top level configuration before passing the configuration to build each output.
Fixes #106.
> Merge top level configuration

- README.md
- lib/logstash-logger/device.rb
- lib/logstash-logger/device/kinesis.rb
- logstash-logger.gemspec
- spec/device/kinesis_spec.rb
- spec/spec_helper.rb
https://aws.amazon.com/kinesis/streams/
> Add support for logging to AWS Kinesis (basically a hosted Kafka)

- README.md
- lib/logstash-logger/device/tcp.rb
- spec/device/tcp_spec.rb
Verifying SSL host against the certificate provided.
Certificate host expiry, etc is checked only as a manual step after connection. It is not an automatic action in OpenSSL. This enables that check.
This means that:
- self signed certs will not work without specifying the SSL context
- hosts with a cert for "my-evil-domain.com" will fail to connect if their host name is "my-real-company.com"
Without these checks, all SSL connections are vulnerable to man in the middle attacks.
> security: Verify SSL certificates

- README.md
- lib/logstash-logger/device.rb
- lib/logstash-logger/device/aws_stream.rb
- lib/logstash-logger/device/firehose.rb
- lib/logstash-logger/device/kinesis.rb
- spec/device/firehose_spec.rb
- spec/spec_helper.rb
AWS Firehose allow direct streaming data to AWS elastic search service. This would allow a seamless delivery of log from hosting machine to ES.
This is mostly mimic what the `Kinesis` device is doing.
> Add support for AWS Firehose

- lib/logstash-logger/formatter/base.rb
Doing the following (an example taken from the README
file)
logger.debug message: 'test', foo: 'bar'
will fail for any logger whose the formatter's class
inherits from LogStashLogger::Formatter::Base when
LogStashLogger.configuration.max_message_size is
set. This happens because event['message'.freeze].byteslice
(previously on line 49) will fail as
event['message'.freeze] will return nil.
> Stringify key :message in the base formatter

- .travis.yml
- Appraisals
- README.md
- gemfiles/rails_4.0.gemfile
- gemfiles/rails_4.1.gemfile
- gemfiles/rails_5.0.gemfile
- gemfiles/rails_5.1.gemfile
- logstash-logger.gemspec
Also drops support for Rails 3.2, and Ruby < 2.2 since these have been EOL'ed.
> Rails 5.1 support

- lib/logstash-logger/formatter/base.rb
- spec/formatter/base_spec.rb
- spec/spec_helper.rb
Hi guys!
I was faced with the following problem:
I'm sending messages and pure JSON objects through UDP, and sometimes some messages can be very large. So i've decided to use `max_message_size` option but i've encountered another problem:
```
Failure/Error: event['message'.freeze] = event['message'.freeze].byteslice(0, LogStashLogger.configuration.max_message_size)
NoMethodError:
undefined method `byteslice' for nil:NilClass
```
cause there is no `message`-field in the JSON-objects.
> Skip message truncating when there is no message field

- lib/logstash-logger/logger.rb
- logstash-logger.gemspec
- spec/syslog_spec.rb
Now there is an inconsistency in creating loggers:
You can create logger with `type: 'file'`, but you will get an error if you would try to create a logger with `type: 'syslog'` or `type: 'multi_logger'`. Syslog and Multi_logger only accept symbol as a type.
I made logger creation the same for 'default logger' and for syslog and multi_logger.
> Allow type to be a string for multi_logger and syslog

- lib/logstash-logger/device/base.rb
- lib/logstash-logger/device/connectable.rb
- lib/logstash-logger/formatter/base.rb
- lib/logstash-logger/formatter/cee.rb
- lib/logstash-logger/formatter/cee_syslog.rb
- lib/logstash-logger/formatter/json.rb
- lib/logstash-logger/formatter/json_lines.rb
- lib/logstash-logger/formatter/logstash_event.rb
- spec/formatter/base_spec.rb
- spec/formatter/cee_syslog_spec.rb
- Moved the responsibility of returning the formatted message to the
base `LogStashLogger::Formatter::Base` class, since it is there where
the event is assembled and possibly cancelled by the user.
- Added a new private `#format_event` method that receives an event and
returns the object to be logged to the device. This method may be
overriden by the derived formatter classes.
- Public interface should be backwards compatible for non-cancelled
events.
- TODO: Do all supported devices gracefully handle a `nil` response
from the formatters?
Resolves #133
> Return `nil` from formatters' `#call` method if the logstash event has been cancelled

- lib/logstash-logger/buffer.rb
- lib/logstash-logger/device/base.rb
- lib/logstash-logger/device/connectable.rb
- lib/logstash-logger/logger.rb
Expose ` #reset` method which will clean up all allocated resources on a LogStashLogger. This is useful when, for example, forking a worker process in a web application, and you don't want to share the parent processes' resources with the children.
See #126
> Reset logger state

- README.md
- lib/logstash-logger/device/aws_stream.rb
- lib/logstash-logger/device/firehose.rb
- lib/logstash-logger/device/kinesis.rb
- spec/device/firehose_spec.rb
`aws-sdk` gem has been split into several gems: https://github.com/aws/aws-sdk-ruby/blob/master/V3_UPGRADING_GUIDE.md
The changed code tries to require a new gem first but keeps backward compatibility with the previous `aws-sdk` gem version.
> Require specific AWS gems for every class

- README.md
- lib/logstash-logger/device/aws_stream.rb
- spec/device/firehose_spec.rb
- spec/device/kinesis_spec.rb
https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/setup-config.html#aws-ruby-sdk-setting-credentials
This will make it use the default credential provider chain which will for example enable to use instance profile.
> Default AWS Credential Provider Chain
